### ISSUE TITLE
how insert &nbsp;?

### ISSUE THREAD

**Issue by rayastar** [python273/telegraph#13] opened 2018-05-31 13:54 UTC
Hello everyone. How i can insert &amp;nbsp?
For example, if i sent` text-1&nbsp;text2` everything OK
But if i try sent 

> `<b>test-1</b>&nbsp;test-2`

 space don't show, text is stuck together
what i must to do?

not correctly:
![image](https://user-images.githubusercontent.com/7265549/40786294-65e21d62-64f3-11e8-8f51-6e7398300345.png)

**Comment by python273** [comment] 2018-06-09 13:04
That's a bug. The problem is that we need to render this html:
```
<p>    
<strong>
     Hello,        </strong>
   world!
   
</p>
```
to "**Hello,** world!" (without new lines and spaces) and to Telegraph format:
```
[
    {'tag': 'p', 'children': [
        {'tag': 'b', 'children': ['Hello, ']},
        'world!'
    ]},
]
```

Now the HTML to Telegraph converter just strips all strings via `s.strip()`, so `<p><b>Hello</b> world!</p>` doesn't look correctly.

**Comment by rayastar** [comment] 2018-06-09 19:42
Thank you Kirill for your help!

**Comment by python273** [comment] 2018-06-16 07:35
I pushed fix to master, can you try to install the module from master
`pip install https://github.com/python273/telegraph/archive/master.zip`
and check if everything is ok with `<p><b>Hello</b> world</p>`

**Comment by Bernard04** [comment] 2018-06-21 13:20
It's don't work. And <br> deletes the text after. Examples:

> <p><b>Client:</b></p><b>Fullname:</b>{0}<br><b>Phone:</b>{1}

result: http://telegra.ph/Order-15590631-06-21

**Comment by Bernard04** [comment] 2018-06-21 13:28
oh, okey. `<img>` incorrect work too.
`<img src='https://i.imgur.com/WMDBZtc.png'><br><p><b>Client:</b></p><b>Fullname:</b>{0}<br><b>Phone:</b>{1}`

result: http://telegra.ph/Order-15590631-06-21-3

**Comment by python273** [comment] 2018-06-21 13:36
My output for both documents:
`<p><b>Client:</b></p><b>Fullname:</b>{0}<br><b>Phone:</b>{1}`
http://telegra.ph/Something-06-21

`<img src='https://i.imgur.com/WMDBZtc.png'><br><p><b>Client:</b></p><b>Fullname:</b>{0}<br><b>Phone:</b>{1}`
http://telegra.ph/Something-06-21-2

Are you sure you are using version from master branch? You can install it via:
`pip install https://github.com/python273/telegraph/archive/master.zip`

**Comment by Bernard04** [comment] 2018-06-21 13:42
hmm. yes, i'm using version from master branch. I deleted the old version and installed master branch right now

**Comment by Bernard04** [comment] 2018-06-21 13:49
Sorry, it's my fault. All work good

**Closed** 2018-08-04 19:08 UTC
Labels: bug
